### ISSUE TITLE
Divided wallpaper

### ISSUE THREAD

**Issue by evenif1458** [ArcherCX/500PaperXrawler#1]
![Screenshot_20200105-010754_One UI Home](https://user-images.githubusercontent.com/9044152/71768251-d3c84880-2f57-11ea-9783-44c208d4e390.jpg)
Like this.
I think 500px encrypted pictures..

**Comment by ArcherCX** [comment]
Maybe not , it's likely just a bug which i don't fix (full screen app will trigger this issue) , if that's so,  just slide your screen to see what's happen or tap the picture with three fingers to load next picture.
If neither of these two ways fix it , please tell me here.

**Comment by evenif1458** [comment]
This is the stock launcher for the Galaxy S10+.
I put the icon on only one page so it doesn't scroll the launcher left or
right. The problem persists even after rebooting, so it seems that
interference from full-screen apps is not a problem I think. Of course I
tried clearing cache and tap with three fingers.
2020년 1월 5일 (일) 오전 1:50, ArcherCX <notifications@github.com>님이 작성:

**Comment by ArcherCX** [comment]
I don't have a s10+ on hand, and can't reproduce the problem on my pixel 2.
The easiest way to locate the issue is to export the pictures. I can
provide another apk with export function if you will help me.

**Comment by evenif1458** [comment]
OK I think I can check that apk.

2020년 1월 5일 (일) 오후 12:40, ArcherCX <notifications@github.com>님이 작성:

> I don't have a s10+ on hand, and can't reproduce the problem on my pixel 2.
> The easiest way to locate the issue is to export the pictures. I can
> provide another apk with export function if you will help me.
>

**Comment by evenif1458** [comment]
OK I'm adding cache.zip, and picking another screenshot on android system wallpaper selector.
My previous guess was wrong.  In the wallpaper selector, the picture is displayed normally.  If so, it seems to be a problem with the actual live wallpaper.
![Screenshot_20200105-202135_Live Wallpaper Picker](https://user-images.githubusercontent.com/9044152/71779527-5e618400-2ffa-11ea-9fdf-9b31384b43ad.jpg)
[cache.zip](https://github.com/ArcherCX/500PaperXrawler/files/4023319/cache.zip)

**Comment by ArcherCX** [comment]
... I've just uploaded the new apk

**Comment by ArcherCX** [comment]
So , now the situation is picture shows correctly in the system wallpaper selector, but not in the home screen, am I right.

**Comment by evenif1458** [comment]
already did on v1.1

2020년 1월 5일 (일) 오후 8:33, ArcherCX <notifications@github.com>님이 작성:

**Comment by evenif1458** [comment]
Yes that's it

2020년 1월 5일 (일) 오후 8:35, ArcherCX <notifications@github.com>님이 작성:

**Comment by ArcherCX** [comment]
It's weird, because even the system wallpaper selector, it calls app's live wallpaper service eventually,. I will have to dig my code , it may take a while, I've not touched this project for a long time.

**Comment by ArcherCX** [comment]
Hey @evenif1458 , before I dig into the code, if you can offer some information will be very useful.
Here is the information i need:
1、The screenshot of the divided wallpaper again, and this time with the raw picture you export. BTW, I'm not sure this divided wallpaper is a mixture of two raw pictures or just one picture which been display with some offsets, so maybe there are two raw pictures. 
Or you can just pack the whole directory which contains all exported files and send it to me. 
2、If you're convenient, record your screen while you slide the launcher would be much better.

**Comment by evenif1458** [comment]
https://drive.google.com/folderview?id=1PrjlpYPxTIGlf9Il_DAX3fAaFpyABi1C
cache(2).zip and recorded one.
Sorry I forgot to get actual screenshot, I think video could show it.

**Comment by ArcherCX** [comment]
It's ok, thanks

**Comment by ArcherCX** [comment]
Sorry have not made enough time for this issue in the past few days.
I have got some clues and tried to fix this, please check the new apk to see if the problem is still.
I also saw the parallax scrolling effect not work on your phone and after rotate screen, the wallpaper doesn't rotate as well.For these issues, if this new apk doesn't fix them, i will a new apk to get  more runtime log if you will.
Waiting for your feedback.

**Comment by evenif1458** [comment]
I'm waiting for apk release..

2020년 1월 11일 (토) 오전 3:48, ArcherCX <notifications@github.com>님이 작성:

**Comment by ArcherCX** [comment]
Forget to mention it, I replaced the old apk of v1.1 Just for debug with
new one, so now that's the new apk.

**Comment by ArcherCX** [comment]
Hey @evenif1458 , does the new apk work well ?

**Comment by evenif1458** [comment]
Oh I forgot to reply that.
...Not well.

2020년 1월 11일 (토) 오후 9:46, ArcherCX <notifications@github.com>님이 작성:

**Comment by ArcherCX** [comment]
Still show the divided wallpaper like the screenshot?

**Comment by Pluto-Lu** [comment]
I have the same problem on my sumsung A70 ,too.
I tested the v1.1 apk, and the result  is that picture shows correctly in the system wallpaper selector, but not in the home screen.
Observation 1: Differences, compared to v1.0, is that the position of the divided line varies, and some of the image may show correctly with no divided line.
Observation 2: (see images below) The position of the divided line can change after opening and leaving the app 500PaperXrawer.
Observation 3: All the Images *.webp in the export directory seem correct.
![Issue1](https://user-images.githubusercontent.com/60788961/74048816-e4b02200-4a0d-11ea-9b8d-30474e5026b0.jpg)
![Issue2](https://user-images.githubusercontent.com/60788961/74048817-e679e580-4a0d-11ea-94e3-8a5200064702.jpg)

**Comment by ArcherCX** [comment]
@Pluto-Lu Samsung's default launcher doens't support parallex effect, when swipe screen, the default launcher doesn't pass correct offset to the wallpaper service, that cause the divided paper. 
I will offer disable parallax effect function soon, or you can give another launcher a try , e.g. Nova.

**Comment by Pluto-Lu** [comment]
> @Pluto-Lu Samsung's default launcher doens't support parallex effect, when swipe screen, the default launcher doesn't pass correct offset to the wallpaper service, that cause the divided paper.
> I will offer disable parallax effect function soon, or you can give another launcher a try , e.g. Nova.

Yes, with Nova, the wallpaper is correctly shown.
Thanks for the good program and look forward to the new functions.

**Comment by ArcherCX** [comment]
Version 2.0 offer a switch to control whether enable parallax effect.
Or you can intsall another launcher(e.g. nova)
