### ISSUE TITLE
Can the wallpaper set to align-center while turning off the Parallax Effect.

### ISSUE THREAD

**Issue by ronny1020** [ArcherCX/500PaperXrawler#2]
Hi, I love this app. However, I would like to make the wallpaper in the center. I understand it's probably impossible with the Parallax Effect. But is it possible to be align-center while turning off Parallax Effect?

**Comment by ArcherCX** [comment]
Yes, it's possible. If you want all wallpaper align-center, I need some
time to implement. If you just want to change the wallpaper temporarily,
you can double tap the home screen, then slide the picture to reset the
initial location in the open activity.
 Tip: As the Android system restriction, if the activity doesn't show, just
click the system navigation back button and try again.

**Comment by ArcherCX** [comment]
Sorry it took so long, I made some time to implement this new feature recently. 
Mainly I add a switch in settings, which called "Adjust Show Area Permanently", enable it will show a new item, click new item will open a wallpaper detail page like double tap. 
Did't test in many phones, but it should work well, just give it a try, hope you like it.
Thanks

**Comment by ronny1020** [comment]
Thank you for your efforts. It's great. I really like this feature.
There is one small issue though, when I correct landscape photos, portrait photos don't seem to work well and vice versa.

**Comment by ArcherCX** [comment]
Hey @ronny1020 ,  I'm checking the issue, but I need confirm some details. When you refer to either landscape or portrait, do you mean just the photo content type or the screen orientation? Can you post some screenshots or a screen record video? I know there are some issues when deal with rotate screen, but I'm not sure if it is what you refer to.

**Comment by ronny1020** [comment]
Thanks for your reply. I mean the photo content type. I haven't tried the screen rotation. It is just like if I set a landscape photo to align center when the wallpaper is changed to a  portrait photo, It wouldn't align to center.

**Comment by ArcherCX** [comment]
Sorry I can't reproduce the issue, but I wonder how did you open the wallpaper detail page. 
There are two entrances to the wallpaper detail page, double tap and a menu item in the app's main page(this menu item only appears when switch "Adjust Show Area Permanently" is enabled), entry through double tap and adjust only affect current photo, but adjust through menu item will affect all photos.

**Comment by ArcherCX** [comment]
Ok, I will check that tomorrow. And if you have time to post some
screenshots, that would be great.

**Comment by ronny1020** [comment]
Hi, thanks for the reply. However, actually, I can't use this app recently. I can't get any images from the app properly.

**Comment by ArcherCX** [comment]
There ara two cases if you can't get any image.
Case 1: Somehow app doesn't work properly, in most cases,  force stop the app or reinstall will fix it.
Case 2: Your internet can't connect to 500px server, you can access 500px.com via browser directly to check the connectivity.

**Comment by ronny1020** [comment]
Sorry for the late reply. It works well again. By the way, after reinstalling it. I can't reproduce the alignment issue. Thank you a lot.
